import * as anchor from "@project-serum/anchor";
import { PublicKey } from "@solana/web3.js";
import { OptionMarketWithKey } from "@mithraic-labs/psy-american";
const optionMarketData: OptionMarketWithKey[] =  
    [{
        optionMint: new PublicKey(1),
        writerTokenMint:new  PublicKey(1),
        underlyingAssetMint:new  PublicKey(1),
        quoteAssetMint: new PublicKey(1),
        underlyingAssetPool:new  PublicKey(1),
        quoteAssetPool:new  PublicKey(1),
        mintFeeAccount: new  PublicKey(1),
        exerciseFeeAccount:new  PublicKey(1),
        underlyingAmountPerContract:new  anchor.BN(2),
        quoteAmountPerContract: new  anchor.BN(1),
        expirationUnixTimestamp: new  anchor.BN(1),
        expired: true,
        bumpSeed: 1,
        key: new PublicKey(1),
    }, 
    {
        optionMint: new PublicKey(2),
        writerTokenMint:new  PublicKey(2),
        underlyingAssetMint:new  PublicKey(2),
        quoteAssetMint: new PublicKey(2),
        underlyingAssetPool:new  PublicKey(2),
        quoteAssetPool:new  PublicKey(2),
        mintFeeAccount: new  PublicKey(2),
        exerciseFeeAccount:new  PublicKey(2),
        underlyingAmountPerContract:new  anchor.BN(20),
        quoteAmountPerContract: new  anchor.BN(200),
        expirationUnixTimestamp: new  anchor.BN(2),
        expired: true,
        bumpSeed: 2,
        key: new PublicKey(2),
    },
    {
        optionMint: new PublicKey(4),
        writerTokenMint:new  PublicKey(4),
        underlyingAssetMint:new  PublicKey(4),
        quoteAssetMint: new PublicKey(4),
        underlyingAssetPool:new  PublicKey(4),
        quoteAssetPool:new  PublicKey(4),
        mintFeeAccount: new  PublicKey(4),
        exerciseFeeAccount:new  PublicKey(4),
        underlyingAmountPerContract:new  anchor.BN(1),
        quoteAmountPerContract: new  anchor.BN(4),
        expirationUnixTimestamp: new  anchor.BN(4),
        expired: true,
        bumpSeed: 4,
        key: new PublicKey(4),
    },
    {
        optionMint: new PublicKey(5),
        writerTokenMint:new  PublicKey(5),
        underlyingAssetMint:new  PublicKey(5),
        quoteAssetMint: new PublicKey(5),
        underlyingAssetPool:new  PublicKey(5),
        quoteAssetPool:new  PublicKey(5),
        mintFeeAccount: new  PublicKey(5),
        exerciseFeeAccount:new  PublicKey(5),
        underlyingAmountPerContract:new  anchor.BN(5),
        quoteAmountPerContract: new  anchor.BN(5),
        expirationUnixTimestamp: new  anchor.BN(5),
        expired: true,
        bumpSeed: 5,
        key: new PublicKey(5),
    },
    {
        optionMint: new PublicKey(6),
        writerTokenMint:new  PublicKey(6),
        underlyingAssetMint:new  PublicKey(6),
        quoteAssetMint: new PublicKey(6),
        underlyingAssetPool:new  PublicKey(6),
        quoteAssetPool:new  PublicKey(6),
        mintFeeAccount: new  PublicKey(6),
        exerciseFeeAccount:new  PublicKey(6),
        underlyingAmountPerContract:new  anchor.BN(6),
        quoteAmountPerContract: new  anchor.BN(6),
        expirationUnixTimestamp: new  anchor.BN(6),
        expired: true,
        bumpSeed: 6,
        key: new PublicKey(6),
    },
    {
        optionMint: new PublicKey(7),
        writerTokenMint:new  PublicKey(7),
        underlyingAssetMint:new  PublicKey(7),
        quoteAssetMint: new PublicKey(7),
        underlyingAssetPool:new  PublicKey(7),
        quoteAssetPool:new  PublicKey(7),
        mintFeeAccount: new  PublicKey(7),
        exerciseFeeAccount:new  PublicKey(7),
        underlyingAmountPerContract:new  anchor.BN(7),
        quoteAmountPerContract: new  anchor.BN(7),
        expirationUnixTimestamp: new  anchor.BN(7),
        expired: true,
        bumpSeed: 7,
        key: new PublicKey(7),
    },
    {
        optionMint: new PublicKey(8),
        writerTokenMint:new  PublicKey(8),
        underlyingAssetMint:new  PublicKey(8),
        quoteAssetMint: new PublicKey(8),
        underlyingAssetPool:new  PublicKey(8),
        quoteAssetPool:new  PublicKey(8),
        mintFeeAccount: new  PublicKey(8),
        exerciseFeeAccount:new  PublicKey(8),
        underlyingAmountPerContract:new  anchor.BN(8),
        quoteAmountPerContract: new  anchor.BN(8),
        expirationUnixTimestamp: new  anchor.BN(8),
        expired: true,
        bumpSeed: 8,
        key: new PublicKey(1),
    },
    {
        optionMint: new PublicKey(9),
        writerTokenMint:new  PublicKey(9),
        underlyingAssetMint:new  PublicKey(9),
        quoteAssetMint: new PublicKey(9),
        underlyingAssetPool:new  PublicKey(9),
        quoteAssetPool:new  PublicKey(9),
        mintFeeAccount: new  PublicKey(9),
        exerciseFeeAccount:new  PublicKey(9),
        underlyingAmountPerContract:new  anchor.BN(9),
        quoteAmountPerContract: new  anchor.BN(9),
        expirationUnixTimestamp: new  anchor.BN(9),
        expired: true,
        bumpSeed: 9,
        key: new PublicKey(9),
    },
    {
        optionMint: new PublicKey(3),
        writerTokenMint:new  PublicKey(3),
        underlyingAssetMint:new  PublicKey(3),
        quoteAssetMint: new PublicKey(3),
        underlyingAssetPool:new  PublicKey(3),
        quoteAssetPool:new  PublicKey(3),
        mintFeeAccount: new  PublicKey(3),
        exerciseFeeAccount:new  PublicKey(3),
        underlyingAmountPerContract:new  anchor.BN(3),
        quoteAmountPerContract: new  anchor.BN(3),
        expirationUnixTimestamp: new  anchor.BN(3),
        expired: true,
        bumpSeed: 3,
        key: new PublicKey(3),
    },
]
    
    
export default optionMarketData;